### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by N4nsh** [usehenri/henri#62]
I tried to install the frameworks on Windows.
So I followed the guide:
`npm i -g henri`
`npm i @usehenri/disk`

Then I had this issue:
```
C:\Users\Nathan\Desktop\projects\rocket-elevators>henri server

       henri ✏  0.34.4-alpha.1 => dev +10ms                                                                     15:29:56

        boot ✏  running from cli                                                                                15:29:56
     modules ✏  config => loaded => 1/10 +8ms                                                                   15:29:56
        mail ✏  no mail configuration found                                                                     15:29:56
     graphql ✏  graphql playground started                                                                      15:29:56
     modules ✏  mail => loaded => 2/10 +6ms                                                                     15:29:56
     modules ✏  graphql => loaded => 3/10                                                                       15:29:56
     modules ✏  controllers => loaded => 4/10 +9ms                                                              15:29:56
     modules ✏  server => loaded => 5/10                                                                        15:29:56
     modules ✏  runlevel 3 => Cannot find module 'C:\Users\Nathan\Desktop\projects\rocket-elevators\node_modules\@usehenri\react\engine\index' +645ms          15:29:57
     modules ✏  init => unable to init correctly                                                                15:29:57

     promise ✏  Error: henri - unable to execute init()                                                         15:29:57

     promise ✏      at Promise (C:\Users\Nathan\AppData\Roaming\npm\node_modules\henri\node_modules\@usehenri\core\src\henri.js:79:15) +6ms          15:29:57
     promise ✏      at <anonymous>                                                                              15:29:57
     promise ✏      at process._tickCallback (internal/process/next_tick.js:188:7)                              15:29:57
     promise ✏      at startup (bootstrap_node.js:191:16)                                                       15:29:57
     promise ✏      at bootstrap_node.js:612:3 +2ms
```

After doing `npm i @usehenri/react` asked by Reel I get a new error:
```
C:\Users\Nathan\Desktop\projects\rocket-elevators>henri server

       henri ✏  0.34.4-alpha.1 => dev +33ms                                                                     16:06:22

        boot ✏  running from cli                                                                                16:06:22
     modules ✏  config => loaded => 1/10 +13ms                                                                  16:06:22
        mail ✏  no mail configuration found                                                                     16:06:22
     graphql ✏  graphql playground started                                                                      16:06:22
     modules ✏  mail => loaded => 2/10                                                                          16:06:22
     modules ✏  graphql => loaded => 3/10 +6ms                                                                  16:06:22
     modules ✏  controllers => loaded => 4/10 +12ms                                                             16:06:22
     modules ✏  server => loaded => 5/10                                                                        16:06:22
     modules ✏  runlevel 3 => Cannot find module '@zeit/next-sass' +3155ms                                      16:06:25
     modules ✏  init => unable to init correctly                                                                16:06:25

     promise ✏  Error: henri - unable to execute init() +9ms                                                    16:06:25

     promise ✏      at Promise (C:\Users\Nathan\AppData\Roaming\npm\node_modules\henri\node_modules\@usehenri\core\src\henri.js:79:15)           16:06:25
     promise ✏      at <anonymous>                                                                              16:06:25
     promise ✏      at process._tickCallback (internal/process/next_tick.js:188:7) +6ms                         16:06:25
     promise ✏      at startup (bootstrap_node.js:191:16)                                                       16:06:25
     promise ✏      at bootstrap_node.js:612:3
```

**Comment by reel** [comment]
Can you try to install `@zeit/next-sass`

Node seems to be able to resolve it on Linux. 

Also, make sure that you don't have any errors while installing @zeit/next-sass

**Comment by reel** [comment]
Does your `package.json` looks like this file:

https://github.com/usehenri/henri/blob/master/packages/cli/template/default/package.json

**Comment by reel** [comment]
The failure in the log is `Cannot find module '...\node_modules\@usehenri\react\engine\index'`: the application was configured for the React renderer without depending on it. That was a real papercut, and it is answered now rather than left to a stack trace.

- The renderer is a dependency of the application, which `henri new` writes into `package.json` for you.
- `henri doctor` reports a configured renderer that is not installed, with the install line.
- `henri build` fails with `@usehenri/inertia is not installed in this project` instead of a module resolution error.
- And as of #353, an application that installed a renderer but never set `renderer` is told at boot rather than quietly rendering handlebars.

The report is against 0.34.4-alpha.1 from 2018 and cannot be reproduced against the current CLI. Closing as fixed; please reopen with the output of `henri doctor` if a fresh install on Windows still goes wrong.
